FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY target/paymentservice-0.0.1-SNAPSHOT.jar payment-service.jar

EXPOSE 8085

ENV STRIPE_API_KEY=${STRIPE_API_KEY}
ENV STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
ENV VNPAY_API_KEY=${VNPAY_API_KEY}
ENV VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:mysql://localhost:3306/payment_db}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-root}

ENTRYPOINT ["java", "-jar", "payment-service.jar"]

